#! /bin/sh

die() {
	echo "ERROR: $*" > /dev/console
	poweroff
	exit 1
}

log() {
	echo "LOG: $*" > /dev/console
}

grep -q ximage /proc/cmdline || exit 0

/bin/diskim mount
/bin/diskim copy
if grep -q bootable /proc/cmdline; then
	log Bootable
	/bin/diskim bootable
fi
/bin/diskim umount
log SUCCESS
poweroff
