#! /bin/sh

prg=$(basename $0)
dir=$(dirname $0); dir=$(readlink -f $dir)
tmp=${TMPDIR:-/tmp}/${prg}_$$
sh=$(readlink -f $dir/../../diskim.sh)
die() {
	echo "ERROR: $*" >&2
	rm -rf $tmp
	exit 1
}
eval $($sh env)

test -n "$1" || die 'No file'
test -x $sh || die "Not executable [$sh]"
kernel=$__kobj/bzImage
test -r $kernel || die "Not readable [$kernel]"

mkdir -p $tmp
cp -R $dir/rootfs/* $tmp
$sh busybox_install --dest=$tmp || die "Failed to install BusyBox"
ln -s $kernel $tmp/boot/bzImage
make -C $__kobj INSTALL_MOD_PATH=$tmp modules_install 1>&2 || \
	die "Failed to install kernel modules"
rm -f $(find $tmp/lib -type l)
cd $tmp
tar --dereference -cf $1 *
cd - > /dev/null
rm -rf $tmp
