#! /bin/sh
/bin/busybox mkdir -p /sbin /var/log /var/run /proc /sys /tmp
/bin/busybox --install -s

mount -t sysfs sysfs /sys
mount -t proc procfs /proc
mdev -s

# This is only for test purposes. By allowing a switch_root here we
# can test an image made from the initrd.cpio.
if grep 'root=/dev/vda' /proc/cmdline && test -z "$1"; then
	echo "Switch root..."
	mkdir /mnt
	mount -t ext4 /dev/vda /mnt
	mkdir -p /mnt/dev
	cp -R /dev/console /mnt/dev 
	exec switch_root -c /dev/console /mnt /init disk
fi

exec /sbin/init
